spring.application.name=WeatherApp
weather.api.key = 8742a2e2834340b391680519263103
weather.api.url = http://api.weatherapi.com/v1/current.json
weather.api.forecast.url = http://api.weatherapi.com/v1/forecast.json